<a href="https://colab.research.google.com/github/royalsky13/Car-Information-Dataset-EDA-with-Python/blob/main/Worksheet9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

I will practice worksheet 9 codes in this Notebook.

In [1]:
print('Hello World!') # printing something

# adding two numbers
# in python <- is not used
num1 = 2
num2 = 8
add = num1 + num2

# can print in these ways
print(add)
print('The sum of {0} and {1} is {2}'.format(num1, num2, add))

# square root of a number
a = 90
print(a** 0.5)

# exponents
print(4**5)

Hello World!
10
The sum of 2 and 8 is 10
9.486832980505138
1024


# **1. Write a function that takes two matrices as input and returns the diagonals of the sum of the two matrices.**

In [11]:
import numpy as np
def diagonalmatrix (matrix_1,matrix_2):
  matrix_1 = np.array(matrix_1)
  matrix_2 = np.array(matrix_2)
  print (matrix_1.diagonal())
  print (matrix_2.diagonal())

diagonalmatrix(matrix_1= [[1,2,3],[2,3,4],[4,5,6]],matrix_2= [[7,2,4],[2,9,4],[5,7,8]])


[1 3 6]
[7 9 8]


In [5]:
np.array([[1,2,3],[2,3,4]]).diagonal()

array([1, 3])

# **2. Write a function that outputs a a 5 x 2 matrix of random integers 1 and 15 (both inclusive).**

In [26]:
import random as ran
import numpy as np
def random_integer_matrix (shape):
  for i in range(0:shape[0]):
    for j in range(0:shape[1]):
      a[i,j]=ran.random(0,16)
return a


random_integer_matrix(shape=[5,2])




SyntaxError: ignored

In [24]:
range(0,10,1)

range(0, 10)

In [15]:
np.array([[1,2,3],[2,3,4]]).shape

(2, 3)

# 3. Write a function that takes an argument (n) and calculates n!.

In [31]:
def factorial (n):
  fact=1
  for i in range(n,1,-1):
    fact=fact*i
  return fact

n=6
print("The factorial of factorial {} is {}.".format(n,factorial(n)))


The factorial of factorial 6 is 720.


# 4. Write a function to count the number of random [0, 1] draws it takes for their sum to exceed 1. The function should have no inputs and should return just one numeric output. Further, write a program to call the above function 1000 times and store all 1000 outputs in a numeric vector. Print the average of the 1000 outputs.

In [48]:
import random as ran
def random_draws():
  sum = 0
  count = 0
  while (True):
    draw =ran.uniform(0,1)
    sum=sum+draw
    count=count+1
    if (sum>1):
      break
  return count

def throws():
  for i in range(1,100):
    a[i]= random_draws ()
  return a

throws()


TypeError: ignored

SyntaxError: ignored

In [58]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

webpage = requests.get("https://editorial.rottentomatoes.com/guide/movies-100-percent-score-rotten-tomatoes/")
soup = BeautifulSoup(webpage.content, "html.parser")
soup

<!DOCTYPE html>

<html class="hitim" lang="en-US">
<head prefix="og: http://ogp.me/ns# flixstertomatoes: http://ogp.me/ns/apps/flixstertomatoes#">
<meta content="text/html; charset=utf-8" http-equiv="content-type"/>
<!-- OneTrust Cookies Consent Notice start for rottentomatoes.com -->
<script charset="UTF-8" crossorigin="anonymous" data-domain-script="7e979733-6841-4fce-9182-515fac69187f" integrity="sha384-WEHwEli88wqOiQd913F1utFZiwisa8XhCkbjLnbKEpFa/WbFcPKeGg7h4fdsv0Z/" src="https://cdn.cookielaw.org/consent/7e979733-6841-4fce-9182-515fac69187f/otSDKStub.js" type="text/javascript">
</script>
<script type="text/javascript">
        function OptanonWrapper() { }
    </script>
<!-- OneTrust Cookies Consent Notice end for rottentomatoes.com -->
<!-- OneTrust IAB US Privacy (USP) -->
<script ccpa-opt-out-geo="US" ccpa-opt-out-ids="dummy" ccpa-opt-out-lspa="false" charset="UTF-8" src="https://cdn.cookielaw.org/opt-out/otCCPAiab.js" type="text/javascript">
</script>
<!-- OneTrust IAB US Priv

In [59]:

example_column = soup.find_all(attrs={"class": "article_movie_title"})
example_column

[<div class="article_movie_title" style="float: left;">
 <div><h2><a href="https://www.rottentomatoes.com/m/leave_no_trace">Leave No Trace</a> <span class="subtle start-year">(2018)</span> <span class="icon tiny certified" title="Certified Fresh"></span> <span class="tMeterScore">100%</span></h2></div>
 </div>,
 <div class="article_movie_title" style="float: left;">
 <div><h2><a href="https://www.rottentomatoes.com/m/toy_story_2">Toy Story 2</a> <span class="subtle start-year">(1999)</span> <span class="icon tiny certified" title="Certified Fresh"></span> <span class="tMeterScore">100%</span></h2></div>
 </div>,
 <div class="article_movie_title" style="float: left;">
 <div><h2><a href="https://www.rottentomatoes.com/m/man_on_wire">Man on Wire</a> <span class="subtle start-year">(2008)</span> <span class="icon tiny certified" title="Certified Fresh"></span> <span class="tMeterScore">100%</span></h2></div>
 </div>,
 <div class="article_movie_title" style="float: left;">
 <div><h2><a href

In [67]:
example_list = []
for x in example_column:
  foo=x.find('a')
  example_list.append(foo.get_text())
#example_;ist.append(x.get_text())

example_list



['Leave No Trace',
 'Toy Story 2',
 'Man on Wire',
 'Honeyland',
 'Minding the Gap',
 'His House',
 'The Philadelphia Story',
 '76 Days',
 'Crip Camp',
 'Summer 1993',
 'The Tale of the Princess Kaguya',
 'Toy Story',
 'One Cut of the Dead',
 'No Bears',
 'Seven Samurai',
 'Taxi to the Dark Side',
 'Gett: The Trial of Viviane Amsalem',
 'Quo Vadis, Aida?',
 "Singin' in the Rain",
 'Welcome to Chechnya',
 'Hive',
 'Deliver Us From Evil',
 'Poetry',
 'Waste Land',
 'The Square',
 'Seymour: An Introduction',
 'All In: The Fight for Democracy',
 'The Terminator',
 'Laura',
 'Mucho Mucho Amor: The Legend of Walter Mercado',
 'Still Walking',
 'Afghan Star',
 'Dawson City: Frozen Time',
 'The Last Picture Show',
 'M',
 'Slalom',
 '12 Angry Men',
 'Athlete A',
 'Pinocchio',
 'Only Yesterday',
 'Three Colors: Red',
 'The Work',
 'Bright Lights: Starring Carrie Fisher and Debbie Reynolds',
 'Attica',
 'Last Train Home',
 'Tampopo',
 'A Secret Love',
 'The Treasure of the Sierra Madre',
 'O.J.: 